In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("/content/Iris.csv")
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [4]:
### Feature and targets
#x = data[["SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"]].values
x = data.iloc[:,1:5].values
y = data.iloc[:,5].values

In [5]:
type(y)

numpy.ndarray

In [6]:
### Split the data into training and testing
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,train_size=0.80,random_state=3)

In [7]:
import numpy as np
np.unique(y,return_counts=True)

(array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object),
 array([50, 50, 50]))

In [8]:
np.unique(ytrain,return_counts=True)

(array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object),
 array([40, 40, 40]))

In [9]:
a = np.unique(ytrain,return_counts=True)

In [10]:
a[1][0] == a[1][1] == a[1][2]

True

In [11]:
### Build the model
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors = 10)

In [12]:
model.fit(xtrain,ytrain)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [13]:
ypred = model.predict(xtest)

In [14]:
ypred

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor'], dtype=object)

In [15]:
ytest

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor'], dtype=object)

In [16]:
df = pd.DataFrame()
df["Actual"] = ytest
df["Predicted"] = ypred
df

Actual        Predicted
0       Iris-setosa      Iris-setosa
1       Iris-setosa      Iris-setosa
2       Iris-setosa      Iris-setosa
3       Iris-setosa      Iris-setosa
4       Iris-setosa      Iris-setosa
5    Iris-virginica   Iris-virginica
6   Iris-versicolor  Iris-versicolor
7       Iris-setosa      Iris-setosa
8    Iris-virginica   Iris-virginica
9   Iris-versicolor  Iris-versicolor
10  Iris-versicolor  Iris-versicolor
11      Iris-setosa      Iris-setosa
12  Iris-versicolor  Iris-versicolor
13  Iris-versicolor  Iris-versicolor
14   Iris-virginica   Iris-virginica
15      Iris-setosa      Iris-setosa
16  Iris-versicolor  Iris-versicolor
17   Iris-virginica   Iris-virginica
18   Iris-virginica   Iris-virginica
19      Iris-setosa      Iris-setosa
20   Iris-virginica   Iris-virginica
21   Iris-virginica   Iris-virginica
22   Iris-virginica   Iris-virginica
23  Iris-versicolor  Iris-versicolor
24      Iris-setosa      Iris-setosa
25   Iris-virginica   Iris-virginica
26   Iris-virginica   Iris-virginica
27  Iris-versicolor  Iris-versicolor
28  Iris-versicolor  Iris-versicolor
29  Iris-versicolor  Iris-versicolor

In [17]:
count = 0
for i in range(len(ytest)):
  if ytest[i] == ypred[i]:
    count = count + 1

In [18]:
count

30

In [19]:
wrong_count = len(ytest) - count
wrong_count

0

In [20]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest,ypred)
cm

array([[10,  0,  0],
       [ 0, 10,  0],
       [ 0,  0, 10]])

In [21]:
29/30

0.9666666666666667

In [22]:
from sklearn.metrics import accuracy_score
accu = accuracy_score(ytest,ypred)
accu

1.0

In [23]:
accuracy = []
for k in range(3,101):
  m = KNeighborsClassifier(n_neighbors = k)
  m.fit(xtrain,ytrain)
  yp = m.predict(xtest)
  ac = accuracy_score(ytest,yp)
  accuracy.append(ac)

In [ ]:
accuracy

In [ ]:
import matplotlib.pyplot as plt
plt.figure(figsize=(15,6))
plt.plot(range(3,101),accuracy,label="K vs Accuracy Graph"
    ,linestyle="dashed",marker="o",markerfacecolor="red")
plt.show()

In [27]:
t_ypred = model.predict(xtrain)
a = accuracy_score(ytrain,t_ypred)
a

0.9666666666666667

In [28]:
model.predict([[2.3,5.6,4.5,6.7]])

array(['Iris-virginica'], dtype=object)

In [34]:
### Save the model
import joblib
joblib.dump(model,"knn.pkl")

['knn.pkl']

In [32]:
mymodel = joblib.load("/content/knn.pkl")

In [33]:
mymodel.predict([[2.3,5.6,4.5,6.7]])

array(['Iris-virginica'], dtype=object)

In [35]:
def predict_species():
  sl = float(input("Enter Sepal Length:"))
  sw = float(input("Enter Sepal Width:"))
  pl = float(input("Enter Petal Length:"))
  pw = float(input("Enter Petal Width:"))
  spe = model.predict([[sl,sw,pl,pw]])
  print(spe[0])

In [36]:
predict_species()

Enter Sepal Length:2.5
Enter Sepal Width:5.3
Enter Petal Length:2.4
Enter Petal Width:1.2
Iris-setosa
